// 自定义分类列表（用于筛选标签展示、排序）
export const CUSTOM_VIDEO_TYPES = [
  { type: "都市", count: 0 },
  { type: "赘婿", count: 0 },
  { type: "战神", count: 0 },
  { type: "古代言情", count: 0 },
  { type: "现代言情", count: 0 },
  { type: "历史", count: 0 },
  { type: "脑洞", count: 0 },
  { type: "玄幻", count: 0 },
  { type: "电视节目", count: 0 },
  { type: "搞笑", count: 0 },
  { type: "网剧", count: 0 },
  { type: "喜剧", count: 0 },
  { type: "萌宝", count: 0 },
  { type: "神豪", count: 0 },
  { type: "致富", count: 0 },
  { type: "奇幻脑洞", count: 0 },
  { type: "超能", count: 0 },
  { type: "强者回归", count: 0 },
  { type: "甜宠", count: 0 },
  { type: "励志", count: 0 },
  { type: "豪门恩怨", count: 0 },
  { type: "复仇", count: 0 },
  { type: "长生", count: 0 },
  { type: "神医", count: 0 },
  { type: "马甲", count: 0 },
  { type: "亲情", count: 0 },
  { type: "小人物", count: 0 },
  { type: "奇幻", count: 0 },
  { type: "无敌", count: 0 },
  { type: "现实", count: 0 },
  { type: "重生", count: 0 },
  { type: "闪婚", count: 0 },
  { type: "职场商战", count: 0 },
  { type: "穿越", count: 0 },
  { type: "年代", count: 0 },
  { type: "权谋", count: 0 },
  { type: "高手下山", count: 0 },
  { type: "悬疑", count: 0 },
  { type: "家国情仇", count: 0 },
  { type: "虐恋", count: 0 },
  { type: "古装", count: 0 },
  { type: "时空之旅", count: 0 },
  { type: "玄幻仙侠", count: 0 },
  { type: "欢喜冤家", count: 0 },
  { type: "传承觉醒", count: 0 },
  { type: "情感", count: 0 },
  { type: "逆袭", count: 0 },
  { type: "家庭", count: 0 },
];

// 豆瓣原分类 → 自定义分类的映射（兜底规则：无匹配则归为「现实」）
export const TYPE_MAPPER = {
  // 豆瓣常见分类 → 你的自定义分类（按需调整映射关系）
  "剧情": "现实",
  "喜剧": "喜剧",
  "动作": "战神",
  "爱情": "情感",
  "科幻": "超能",
  "悬疑": "悬疑",
  "惊悚": "悬疑",
  "恐怖": "脑洞",
  "纪录片": "历史",
  "动画": "奇幻",
  "古装": "古装",
  "武侠": "高手下山",
  "仙侠": "玄幻仙侠",
  "都市": "都市",
  "奇幻": "奇幻",
  "冒险": "时空之旅",
  "犯罪": "复仇",
  "励志": "励志",
  "家庭": "家庭",
  "战争": "家国情仇",
  "传记": "历史",
  "音乐": "电视节目",
  "歌舞": "电视节目",
  "戏曲": "电视节目",
  "西部": "脑洞",
  "默片": "历史",
  "短片": "网剧",
  "真人秀": "电视节目",
  "脱口秀": "搞笑",
  "儿童": "萌宝",
  "伦理": "豪门恩怨",
  "情色": "成人", // 成人内容单独分类（如需）
  "默认": "现实" // 兜底分类
};

// 快捷获取所有自定义分类的type列表
export const ALL_CUSTOM_TYPES = CUSTOM_VIDEO_TYPES.map(item => item.type);
